// Dial codes for Europe and North America
// Each entry: { label: "Country Name (+code)", code: "+code" }

const dialCodes = [
  // --- Europe ---
  { label: "Albánie (+355)",         code: "+355" },
  { label: "Andorra (+376)",         code: "+376" },
  { label: "Rakousko (+43)",         code: "+43"  },
  { label: "Bělorusko (+375)",       code: "+375" },
  { label: "Belgie (+32)",           code: "+32"  },
  { label: "Bosna a Hercegovina (+387)", code: "+387" },
  { label: "Bulharsko (+359)",       code: "+359" },
  { label: "Chorvatsko (+385)",      code: "+385" },
  { label: "Kypr (+357)",            code: "+357" },
  { label: "Česká republika (+420)", code: "+420" },
  { label: "Dánsko (+45)",           code: "+45"  },
  { label: "Estonsko (+372)",        code: "+372" },
  { label: "Finsko (+358)",          code: "+358" },
  { label: "Francie (+33)",          code: "+33"  },
  { label: "Německo (+49)",          code: "+49"  },
  { label: "Řecko (+30)",            code: "+30"  },
  { label: "Maďarsko (+36)",         code: "+36"  },
  { label: "Island (+354)",          code: "+354" },
  { label: "Irsko (+353)",           code: "+353" },
  { label: "Itálie (+39)",           code: "+39"  },
  { label: "Kosovo (+383)",          code: "+383" },
  { label: "Lotyšsko (+371)",        code: "+371" },
  { label: "Lichtenštejnsko (+423)", code: "+423" },
  { label: "Litva (+370)",           code: "+370" },
  { label: "Lucembursko (+352)",     code: "+352" },
  { label: "Malta (+356)",           code: "+356" },
  { label: "Moldavsko (+373)",       code: "+373" },
  { label: "Monako (+377)",          code: "+377" },
  { label: "Černá Hora (+382)",      code: "+382" },
  { label: "Nizozemsko (+31)",       code: "+31"  },
  { label: "Severní Makedonie (+389)", code: "+389" },
  { label: "Norsko (+47)",           code: "+47"  },
  { label: "Polsko (+48)",           code: "+48"  },
  { label: "Portugalsko (+351)",     code: "+351" },
  { label: "Rumunsko (+40)",         code: "+40"  },
  { label: "Rusko (+7)",             code: "+7"   },
  { label: "Srbsko (+381)",          code: "+381" },
  { label: "Slovensko (+421)",       code: "+421" },
  { label: "Slovinsko (+386)",       code: "+386" },
  { label: "Španělsko (+34)",        code: "+34"  },
  { label: "Švédsko (+46)",          code: "+46"  },
  { label: "Švýcarsko (+41)",        code: "+41"  },
  { label: "Turecko (+90)",          code: "+90"  },
  { label: "Ukrajina (+380)",        code: "+380" },
  { label: "Velká Británie (+44)",   code: "+44"  },

  // --- North America ---
  { label: "Kanada (+1)",            code: "+1"   },
  { label: "Mexiko (+52)",           code: "+52"  },
  { label: "USA (+1)",               code: "+1"   },
];

export default dialCodes;
